environment: development
log_level: 4

server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: hub
  password: password
  dbname: hub
  sslmode: disable

redis:
  enabled: false
  host: localhost
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10

jwt:
  secret: your-secret-key-change-this-in-production
  expiration_hour: 24

cors:
  allowed_origins:
    - http://localhost:3000
    - http://localhost:3001

elasticsearch:
  enabled: false
  addresses:
    - http://localhost:9200
  username: ""
  password: ""
  cloud_id: ""
  api_key: ""
  index_prefix: "hub"