environment: development
log_level: 4

server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: hub
  password: password
  dbname: hub
  sslmode: disable

redis:
  enabled: false
  host: localhost
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10

jwt:
  secret: your-secret-key-change-this-in-production
  expiration_hour: 24

cors:
  allowed_origins:
    - http://localhost:3000
    - http://localhost:3001

smtp:
  host: ""
  port: "587"
  username: ""
  password: ""
  from: "noreply@localhost"
  use_tls: true

elasticsearch:
  enabled: false
  addresses:
    - http://localhost:9200
  username: ""
  password: ""
  cloud_id: ""
  api_key: ""
  index_prefix: "hub"
  # Git LFS storage configuration
lfs:
  # Options: "azure_blob", "s3", "filesystem"
  backend: "azure_blob"
  azure:
    account_name: "<your-account-name>"
    account_key: "<your-account-key>"
    container_name: "<your-container-name>"

# GitHub integration for repository creation and import
github:
  # GitHub API base URL
  api_url: https://api.github.com
  # Personal access token for GitHub operations (set via environment or config)
  # token: <your-github-access-token>
