environment: development
log_level: 4

server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: hub
  password: password
  dbname: hub
  sslmode: disable

jwt:
  secret: your-secret-key-change-this-in-production
  expiration_hour: 24

cors:
  allowed_origins:
    - http://localhost:3000
    - http://localhost:3001

elasticsearch:
  enabled: true
  addresses:
    - http://localhost:9200
  username: ""
  password: ""
  cloud_id: ""
  api_key: ""
  index_prefix: "hub_dev"
  # Git LFS storage configuration for development
lfs:
  backend: "azure_blob"
  azure:
    account_name: "<dev-account-name>"
    account_key: "<dev-account-key>"
    container_name: "<dev-container-name>"

# GitHub integration configuration for development
github:
  client_id: "<dev-github-client-id>"
  client_secret: "<dev-github-client-secret>"
  tokens:
    organizations:
      your-dev-org: "<dev-organization-token>"
    users:
      your-dev-user: "<dev-user-token>"
