# Azure Application Gateway SSL and Security Configuration
apiVersion: v1
kind: Secret
metadata:
  name: hub-azure-ssl-certificate
  namespace: hub
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/component: azure-ssl
type: kubernetes.io/tls
# NOTE: This secret will be automatically managed by cert-manager.

---
# Azure Application Gateway WAF Policy Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-waf-policy-config
  namespace: hub
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/component: azure-waf
data:
  waf-policy.json: |
    {
      "policySettings": {
        "state": "Enabled",
        "mode": "Prevention",
        "requestBodyCheck": true,
        "maxRequestBodySizeInKb": 128,
        "fileUploadLimitInMb": 100
      },
      "managedRules": {
        "managedRuleSets": [
          {
            "ruleSetType": "OWASP",
            "ruleSetVersion": "3.2"
          },
          {
            "ruleSetType": "Microsoft_BotManagerRuleSet",
            "ruleSetVersion": "0.1"
          }
        ]
      },
      "customRules": [
        {
          "name": "RateLimitRule",
          "priority": 1,
          "state": "Enabled",
          "ruleType": "RateLimitRule",
          "rateLimitDuration": "OneMin",
          "rateLimitThreshold": 100,
          "matchConditions": [
            {
              "matchVariables": [
                {
                  "variableName": "RemoteAddr"
                }
              ],
              "operator": "IPMatch",
              "matchValues": [
                "0.0.0.0/0"
              ]
            }
          ],
          "action": "Block"
        }
      ]
    }

---
# Enhanced Azure Ingress with SSL and Security
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hub-ingress-azure-secure
  namespace: hub
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/component: ingress-azure-secure
  annotations:
    # Required annotation for Azure Application Gateway Ingress Controller
    kubernetes.io/ingress.class: azure/application-gateway
    
    # SSL/TLS Configuration
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "hub-azure-ssl-certificate"
    
    # If you have an SSL profile in Azure App Gateway, uncomment:
    # appgw.ingress.kubernetes.io/appgw-ssl-profile: "hub-ssl-profile"
    
    # If you have trusted root certificates, uncomment:
    # appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "hub-root-cert"
    
    # WAF Policy (replace with your Azure WAF Policy resource ID)
    # appgw.ingress.kubernetes.io/waf-policy-for-path: "/subscriptions/{subscription-id}/resourceGroups/{rg}/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/{policy-name}"
    
    # Health probe configuration
    appgw.ingress.kubernetes.io/health-probe-hostname: "hub.a5c.ai"
    appgw.ingress.kubernetes.io/health-probe-port: "8080"
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399"
    appgw.ingress.kubernetes.io/health-probe-interval: "30"
    appgw.ingress.kubernetes.io/health-probe-timeout: "30"
    appgw.ingress.kubernetes.io/health-probe-unhealthy-threshold: "3"
    
    # Performance and reliability settings
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "60"
    appgw.ingress.kubernetes.io/request-timeout: "30"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "false"
    
    # Backend configuration
    appgw.ingress.kubernetes.io/backend-protocol: "http"
    appgw.ingress.kubernetes.io/backend-hostname: "hub.a5c.ai"
    
    # Rule priority (lower number = higher priority)
    appgw.ingress.kubernetes.io/rule-priority: "100"
    
    # Use private IP if Application Gateway is configured with one
    # appgw.ingress.kubernetes.io/use-private-ip: "false"
    
    # Custom frontend port if needed
    # appgw.ingress.kubernetes.io/override-frontend-port: "443"
    
    # Hostname extensions for multi-domain support
    # appgw.ingress.kubernetes.io/hostname-extension: "www.hub.a5c.ai,api.hub.a5c.ai"
    
    # External DNS
    external-dns.alpha.kubernetes.io/hostname: hub.a5c.ai
spec:
  tls:
  - hosts:
    - hub.a5c.ai
    secretName: hub-azure-ssl-certificate
  rules:
  - host: hub.a5c.ai
    http:
      paths:
      # API routes with higher priority
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      # Health and readiness checks
      - path: /api/health
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      - path: /ready
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      # Git protocol endpoints
      - path: /git
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      # Frontend routes (catch-all, lower priority)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hub-frontend-service
            port:
              number: 3000
