apiVersion: v1
kind: ServiceAccount
# Note: Replace placeholder environment variables below with actual Azure credentials and DNS zone identifiers before applying
metadata:
  name: external-dns
  namespace: hub

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: hub

---
# Deployment for external-dns controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.14.2
          args:
            - --source=service
            - --source=ingress
            - --provider=azure
            - --policy=sync
            - --registry=txt
            - --txt-owner-id=hub
            - --azure-resource-group=$(AZURE_RESOURCE_GROUP_NAME)
            - --azure-subscription-id=$(AZURE_SUBSCRIPTION_ID)
            - --domain-filter=$(PUBLIC_DNS_ZONE_NAME)
          env:
            - name: AZURE_TENANT_ID
              value: "$(AZURE_TENANT_ID)"
            - name: AZURE_CLIENT_ID
              value: "$(AZURE_APPLICATION_CLIENT_ID)"
            - name: AZURE_CLIENT_SECRET
              value: "$(AZURE_APPLICATION_CLIENT_SECRET)"
            - name: PUBLIC_DNS_ZONE_NAME
              value: "$(PUBLIC_DNS_ZONE_NAME)"
            - name: AZURE_SUBSCRIPTION_ID
              value: "$(AZURE_SUBSCRIPTION_ID)"
            - name: AZURE_RESOURCE_GROUP_NAME
              value: "$(AZURE_RESOURCE_GROUP_NAME)"
