apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hub-ingress
  namespace: hub
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/component: ingress
  annotations:
    # Azure Application Gateway Ingress Controller configuration
    kubernetes.io/ingress.class: azure/application-gateway
    
    # SSL redirect to ensure HTTPS
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    
    # Let AGIC auto-detect health probes per service
    
    # Connection settings
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "60"
    appgw.ingress.kubernetes.io/request-timeout: "30"
    
    # Backend protocol
    appgw.ingress.kubernetes.io/backend-protocol: "http"
    
    # Cookie-based session affinity
    appgw.ingress.kubernetes.io/cookie-based-affinity: "false"
    
    # Request routing rule priority
    appgw.ingress.kubernetes.io/rule-priority: "100"
    
    # External DNS for automatic DNS record creation
    external-dns.alpha.kubernetes.io/hostname: hub.a5c.ai
    
    # cert-manager automatic certificate provisioning
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - hub.a5c.ai
    secretName: hub-azure-ssl-certificate
  rules:
  - host: hub.a5c.ai
    http:
      paths:
      # API routes go to backend
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      # Health check endpoints
      - path: /api/health
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      - path: /ready
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      # Git protocol endpoints
      - path: /git
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      # All other routes go to frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hub-frontend-service
            port:
              number: 3000
