apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hub-ingress
  namespace: hub
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/component: ingress
  annotations:
    # NGINX Ingress Controller configuration
    kubernetes.io/ingress.class: nginx

    # SSL redirect to ensure HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

    # Backend protocol
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

    # External DNS for automatic DNS record creation
    external-dns.alpha.kubernetes.io/hostname: hub.a5c.ai

    # Use regex to route git operations to backend
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hub.a5c.ai
    secretName: hub-azure-ssl-certificate
  rules:
  - host: hub.a5c.ai
    http:
      paths:
      # API routes go to backend
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      # Health check endpoints
      - path: /api/health
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      - path: /ready
        pathType: Prefix
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      # Git repository operations (must come before catch-all)
      # Matches any path ending with .git and their sub-paths
      - path: /([^/]+)/([^/]+)\.git(/.*)?
        pathType: ImplementationSpecific
        backend:
          service:
            name: hub-backend-service
            port:
              number: 8080
      # All other routes go to frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hub-frontend-service
            port:
              number: 3000
