apiVersion: v1
kind: Secret
metadata:
  name: acr-auth
  namespace: hub
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/component: registry-auth
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "<REGISTRY_URL>": {
          "username": "<AZURE_APPLICATION_CLIENT_ID>",
          "password": "<AZURE_APPLICATION_CLIENT_SECRET>",
          "email": "unused"
        }
      }
    }
