apiVersion: v1
kind: Secret
metadata:
  name: hub-secrets
  namespace: hub
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  # Example: echo -n "postgresql://username:password@postgresql:5432/hub?sslmode=require" | base64
  database-url: cG9zdGdyZXNxbDovL3VzZXJuYW1lOnBhc3N3b3JkQHBvc3RncmVzcWw6NTQzMi9odWI/c3NsbW9kZT1yZXF1aXJl
  
  # Redis connection (base64 encoded)
  # Example: echo -n "redis://redis:6379/0" | base64
  redis-url: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  
  # JWT signing secret (base64 encoded)
  # Example: echo -n "your-super-secret-jwt-key-here" | base64
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJl
  
  # GitHub OAuth credentials (base64 encoded)
  # Example: echo -n "your-github-client-id" | base64
  github-oauth-client-id: eW91ci1naXRodWItY2xpZW50LWlk
  # Example: echo -n "your-github-client-secret" | base64
  github-oauth-client-secret: eW91ci1naXRodWItY2xpZW50LXNlY3JldA==
  
  # Database individual credentials (alternative to database-url)  
  # Example: echo -n "hub_user" | base64
  db-username: aHViX3VzZXI=
  # Example: echo -n "secure_password" | base64
  db-password: c2VjdXJlX3Bhc3N3b3Jk
  
  # Admin user credentials
  # Example: echo -n "admin@hub.a5c.ai" | base64
  admin-email: YWRtaW5AaHViLmV4YW1wbGUuY29t
  # Example: echo -n "admin_password" | base64  
  admin-password: YWRtaW5fcGFzc3dvcmQ=
