name: E2E Tests - Production

# This workflow runs end-to-end Playwright tests against the production deployment at hub.a5c.ai.
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Base URL for E2E tests'
        required: false
        default: 'https://hub.a5c.ai'

jobs:
  e2e:
    name: Run E2E Tests on Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright E2E tests
        env:
          BASE_URL: ${{ github.event.inputs.url }}
        run: npm run test:e2e
