name: Infrastructure Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - production

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'development' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ~1.5

    - name: Azure CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_APPLICATION_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_APPLICATION_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Init
      env:
        TF_VAR_environment: ${{ github.event.inputs.environment || 'development' }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_APPLICATION_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_APPLICATION_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        cd terraform/environments/${{ github.event.inputs.environment || 'development' }}
        # Generate backend configuration to avoid interactive prompts
        cat > backend.conf <<EOF
resource_group_name  = "${{ secrets.TFSTATE_RESOURCE_GROUP_NAME }}"
storage_account_name = "${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}"
container_name       = "${{ secrets.TFSTATE_CONTAINER_NAME }}"
key                  = "${{ github.event.inputs.environment || 'development' }}.terraform.tfstate"
EOF
        terraform init -backend-config=backend.conf

    - name: Terraform Validate
      env:
        TF_VAR_environment: ${{ github.event.inputs.environment || 'development' }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_APPLICATION_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_APPLICATION_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        cd terraform/environments/${{ github.event.inputs.environment || 'development' }}
        terraform validate

    - name: Terraform Plan
      env:
        TF_VAR_environment: ${{ github.event.inputs.environment || 'development' }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_APPLICATION_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_APPLICATION_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        cd terraform/environments/${{ github.event.inputs.environment || 'development' }}
        terraform plan -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_APPLICATION_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_APPLICATION_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_environment: ${{ github.event.inputs.environment || 'development' }}
      run: |
        cd terraform/environments/${{ github.event.inputs.environment || 'development' }}
        terraform apply -auto-approve tfplan
