name: Pull Request Automation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Auto-assign reviewers
      uses: kentaro-m/auto-assign-action@v1.2.5
      with:
        configuration-path: '.github/auto-assign.yml'
        
  size-label:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR by size
      uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/xs'
        xs_max_size: 10
        s_label: 'size/s'
        s_max_size: 100
        m_label: 'size/m'
        m_max_size: 500
        l_label: 'size/l'
        l_max_size: 1000
        xl_label: 'size/xl'
        
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Check conventional commits
      uses: wagoid/commitlint-github-action@v5
      with:
        configFile: '.commitlintrc.json'
        
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: moderate
        
  conflict-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check for merge conflicts
      uses: olivernybroe/action-conflict-finder@v4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}