# GitHub action to build

name: Build

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
env:
    DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    NEXTAUTH_URL: http://localhost:4002
    NEXTAUTH_SECRET: secret
    NEXTAUTH_SESSION_STRATEGY: database
    AUTH_PROVIDERS: github,credentials,saml,idp-initiated
    FEATURE_TEAM_SSO: true
    FEATURE_TEAM_DSYNC: true
    FEATURE_TEAM_AUDIT_LOG: true
    FEATURE_TEAM_WEBHOOK: false
    FEATURE_TEAM_API_KEY: true
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    FEATURE_TEAM_DELETION: true
    FEATURE_TEAM_PAYMENTS: true
    CONFIRM_EMAIL: false
    HIDE_LANDING_PAGE: false
    GROUP_PREFIX: a5c-
    DISABLE_NON_BUSINESS_EMAIL_SIGNUP: false
    APP_URL: http://localhost:4002
    JACKSON_PRODUCT_ID: a5c
    JACKSON_WEBHOOK_SECRET: your-webhook-secret
    JACKSON_API_KEY: secret
    DEBUG: pw:webserver
    CI: true
    # vercel credentials
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN || '' }}
    VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID || '' }}
    VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID || '' }}      
    # supabase credentials
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN || '' }}
    SUPABASE_ORG_ID: ${{ vars.SUPABASE_ORG_ID || '' }}
    SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF || '' }}
    SUPABASE_PROJECT_URL:  ${{ vars.SUPABASE_PROJECT_URL || '' }}
    SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD || '' }}
    # slack credentials
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN || '' }}
    SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET || '' }}
    SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN || '' }}
    # discord credentials
    DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN || '' }}
    DISCORD_GUILD_ID: ${{ vars.DISCORD_GUILD_ID || '' }}      
    # access key for stripe api for management
    STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY || '' }}
    # access key for stripe api for payments
    STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY || '' }}
    # webhook secret for stripe
    STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET || '' }}
    # webhook url for stripe
    STRIPE_WEBHOOK_URL: ${{ vars.STRIPE_WEBHOOK_URL || '' }}
    # webhook id for stripe
    STRIPE_WEBHOOK_ID: ${{ vars.STRIPE_WEBHOOK_ID || '' }}
    # aws credentials 
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID || '' }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY || '' }}
    AWS_REGION: ${{ vars.AWS_REGION || '' }}
    # gcloud credentials
    GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS || '' }}
    # azure credentials
    AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID || '' }}
    AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET || '' }}
    AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID || '' }}
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID || '' }}

    # auth credentials
    GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID || '' }}
    GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET || '' }}
    AUTH_GITHUB_CLIENT_ID: ${{ secrets.AUTH_GITHUB_CLIENT_ID || '' }}
    AUTH_GITHUB_CLIENT_SECRET: ${{ secrets.AUTH_GITHUB_CLIENT_SECRET || '' }}
    AUTH_GITHUB_ORG_ID: ${{ vars.AUTH_GITHUB_ORG_ID || '' }}
    AUTH_GITHUB_ORG_NAME: ${{ vars.AUTH_GITHUB_ORG_NAME || '' }}
    AUTH_GITHUB_ORG_DESCRIPTION: ${{ vars.AUTH_GITHUB_ORG_DESCRIPTION || '' }}

    # other credentials
    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY || '' }}
    HEROKU_APP_NAME: ${{ vars.HEROKU_APP_NAME || '' }}
    HEROKU_APP_ID: ${{ vars.HEROKU_APP_ID || '' }}
    HEROKU_APP_URL: ${{ vars.HEROKU_APP_URL || '' }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increased timeout from 15 to 30 minutes
    strategy:
      matrix:
        node-version: [22] 
    steps:
      - uses: actions/checkout@v4
      
      # Setup Go with better caching and proper version specification
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'  # Use go.mod to determine version automatically
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod
          check-latest: true  # Ensure latest available version is used
          
      - name: Setup Node.js with better caching
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json
          check-latest: true
          
      - name: Setup Python with better caching
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
          check-latest: true

      # Optimize Go module download with parallel processing
      - name: Download Go modules
        timeout-minutes: 10
        run: |
          go mod download
          go mod verify
          
      # Build with increased timeout and better error handling
      - name: Build application
        timeout-minutes: 20  # Increased from 10 to 20 minutes
        run: |
          # Set build optimization flags
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=amd64
          
          # Run build with verbose output for debugging
          ./scripts/build.sh
        
      # Upload build artifacts for other jobs with compression
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            frontend/node_modules/
            go.sum
          retention-days: 1
          compression-level: 6  # Balance between speed and size
          
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 25  # Increased from 20 to 25 minutes
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      # Download build artifacts with retry
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          
      # Setup Go with caching and proper version specification
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'  # Use go.mod to determine version automatically
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod
          check-latest: true  # Ensure latest available version is used
          
      - name: Setup Node.js with caching
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json
          check-latest: true
          
      - name: Setup Python with caching
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
          check-latest: true
          
      # Run tests with increased timeout and better error handling
      - name: Run tests
        timeout-minutes: 20  # Increased from 15 to 20 minutes
        run: |
          # Set test environment optimizations
          export GO_TEST_TIMEOUT=10m
          export NODE_OPTIONS="--max-old-space-size=4096"
          
          # Run tests with verbose output
          ./scripts/test.sh
        
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Increased from 15 to 20 minutes
    needs: test
    # Only deploy on main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      # Setup Go with caching and proper version specification
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'  # Use go.mod to determine version automatically
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod
          check-latest: true  # Ensure latest available version is used

      - name: Setup Node.js with caching
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json
          check-latest: true
          
      # Deploy with increased timeout and better error handling
      - name: Deploy application
        timeout-minutes: 15  # Increased from 10 to 15 minutes
        run: |
          # Set deployment optimizations
          export DEPLOY_TIMEOUT=10m
          
          # Run deployment with verbose output
          ./scripts/deploy.sh
